pipeline {

```
agent any

environment {

    PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:${env.PATH}"

}

stages {

    stage('Check Node') {

        steps {

            sh 'which node'
            sh 'node -v'
            sh 'npm -v'

        }

    }

    stage('Install Dependencies') {

        steps {

            dir('DAY-2') {

                sh 'npm install'

            }

        }

    }

    stage('Install Playwright Browsers') {

        steps {

            dir('DAY-2') {

                sh 'npx playwright install --with-deps'

            }

        }

    }

    stage('Run Playwright Tests') {

        steps {

            dir('DAY-2') {

                sh 'npx playwright test --debug'

            }

        }

    }

    stage('Generate Allure Report') {

        steps {

            dir('DAY-2') {

                sh 'npx allure generate allure-results --clean'

            }

        }

    }

}

post {

    always {

        archiveArtifacts(
            artifacts: 'DAY-2/screenshots/**/*',
            allowEmptyArchive: true
        )

        archiveArtifacts(
            artifacts: 'DAY-2/test-results/**/*',
            allowEmptyArchive: true
        )

        archiveArtifacts(
            artifacts: 'DAY-2/playwright-report/**/*',
            allowEmptyArchive: true
        )

        archiveArtifacts(
            artifacts: 'DAY-2/allure-report/**/*',
            allowEmptyArchive: true
        )

    }

}
```

}
